#import = ["alacritty/themes/themes/blood_moon.toml"]
# import = ["alacritty/themes/themes/paper_color_dark.toml"]
[general]
 #import = ["themes/themes/alabaster.toml"]
import = ["themes/themes/paper_color_dark.toml"]

[terminal.shell]
args = ['--login']
program = "/bin/zsh"

[cursor]
style = "Beam"

[font]
size = 10.0

[font.normal]
#family = "RobotoMono Nerd Font"
# family = "RecMono Nerd Font"
family = "ShureTechMono Nerd Font"
# family = "Terminess Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.90

[window.padding]
x = 2
y = 2

[terminal]


