--      ██╗    ██╗ █████╗ ██╗     ██╗     ██████╗  █████╗ ██████╗ ███████╗██████╗
--      ██║    ██║██╔══██╗██║     ██║     ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
--      ██║ █╗ ██║███████║██║     ██║     ██████╔╝███████║██████╔╝█████╗  ██████╔╝
--      ██║███╗██║██╔══██║██║     ██║     ██╔═══╝ ██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
--      ╚███╔███╔╝██║  ██║███████╗███████╗██║     ██║  ██║██║     ███████╗██║  ██║
--       ╚══╝╚══╝ ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝

-- ===================================================================
-- Imports
-- ===================================================================


local awful = require("awful")
local gears = require("gears")
local naughty = require("naughty")


-- ===================================================================
-- Initialization
-- ===================================================================

--
-- local is_blurred = false;
--
-- local wallpaper_dir = gears.filesystem.get_configuration_dir() .. "/wallpaper"
-- local wallpaper = wallpaper_dir .. "/wallpaper.jpg"
-- local blurred_wallpaper = wallpaper_dir .. "/blurredWallpaper.png"
--
-- -- File to save the selected wallpaper path
-- local selected_wallpaper_file = gears.filesystem.get_configuration_dir() .. "/selected_wallpaper.txt"
--
-- -- Load the saved wallpaper path or fallback to the default
-- local function load_saved_wallpaper()
--    local file = io.open(selected_wallpaper_file, "r")
--    if file then
--       local path = file:read("*all")
--       file:close()
--       if gears.filesystem.file_readable(path) then
--          return path
--       end
--    end
--    return wallpaper
-- end
--
-- local function getBlurredPath(path)
--   local directory, filename = path:match("(.*/)([^/]+)$")
--   -- Append 'blurred/' to the directory path
--   local new_directory = directory .. "blurred/"
--
--   -- Combine the new directory and the filename
--   local new_path = new_directory .. filename
--
--   return new_path
-- end
--
-- local current_wallpaper = load_saved_wallpaper()
-- blurred_wallpaper = getBlurredPath(current_wallpaper)
--
-- -- Save the selected wallpaper to a file
-- local function save_wallpaper(path)
--    local file = io.open(selected_wallpaper_file, "w")
--    if file then
--       file:write(path)
--       file:close()
--       current_wallpaper = path
--    else
--       naughty.notify({ preset = naughty.config.presets.critical, title = "Error", text = "Failed to save wallpaper!" })
--    end
-- end
--
-- -- Apply the wallpaper to all screens
-- local function apply_wallpaper(path)
--    for s in screen do
--       gears.wallpaper.maximized(path, s, true)
--    end
-- end
--
-- -- Apply the current wallpaper on startup
-- apply_wallpaper(current_wallpaper)
--
-- --- Check if a file or directory exists in this path
-- local function exists(file)
--    local ok, err, code = os.rename(file, file)
--    if not ok then
--       if code == 13 then
--          -- Permission denied, but it exists
--          return true
--       end
--    end
--    return ok, err
-- end
--
-- -- check if blurred wallpaper needs to be created
-- blurred_wallpaper = getBlurredPath(current_wallpaper)
-- if not exists(blurred_wallpaper) then
--    naughty.notify({
--       preset = naughty.config.presets.normal,
--       title = "Wallpaper",
--       text = "Generating blurred wallpaper... " ..blurred_wallpaper
--    })
--    -- uses image magick to create a blurred version of the wallpaper
--    awful.spawn.with_shell("convert -filter Gaussian -blur 0x10 " .. wallpaper .. " " .. blurred_wallpaper)
-- end
--
--
-- -- ===================================================================
-- -- Functionality
-- -- ===================================================================
--
--
-- -- changes to blurred wallpaper
-- local function blur()
--    if not is_blurred then
--        apply_wallpaper(blurred_wallpaper)
--       is_blurred = true
--    end
-- end
--
-- -- changes to normal wallpaper
-- local function unblur()
--    if is_blurred then
--        apply_wallpaper(current_wallpaper)
--       is_blurred = false
--    end
-- end
--
-- -- blur / unblur on tag change
-- tag.connect_signal("property::selected", function(t)
--    -- check if tag has any clients
--    for _ in pairs(t:clients()) do
--       blur()
--       return
--    end
--    -- unblur if tag has no clients
--    unblur()
-- end)
--
-- -- check if wallpaper should be blurred on client open
-- client.connect_signal("manage", function(c)
--    blur()
-- end)
--
-- -- check if wallpaper should be unblurred on client close
-- client.connect_signal("unmanage", function(c)
--    local t = awful.screen.focused().selected_tag
--    -- check if tag has any clients
--    for _ in pairs(t:clients()) do
--       return
--    end
--    -- unblur if tag has no clients
--    unblur()
-- end)
--
--
-- -- [NEW]
-- -- Function to set a new wallpaper
-- local function set_wallpaper(path)
--    save_wallpaper(path)
--    apply_wallpaper(path)
--    blurred_wallpaper = getBlurredPath(path)
--
--    if not exists(blurred_wallpaper) then
--      awful.spawn.with_shell("convert -filter Gaussian -blur 0x30 " .. path .. " " .. blurred_wallpaper)
--    end
-- end
--
-- return {
--    set_wallpaper = set_wallpaper
-- }
-- -- [END NEW]
